using System.Diagnostics;
using System.Text;
using RagnaForge.Application.Abstractions;
using RagnaForge.Domain.Configuration;
using RagnaForge.Domain.Maps;
using RagnaForge.Infrastructure.FileSystem;

namespace RagnaForge.Infrastructure.Maps;

public sealed class RathenaMapCacheBuilder(string workspaceRoot) : IMapCacheBuilder
{
    public MapCacheBuildResult Build(
        RepositoryPaths paths,
        MapCacheBuildRequest request)
    {
        ArgumentNullException.ThrowIfNull(paths);
        ArgumentNullException.ThrowIfNull(request);

        var toolPath = SafeFileSystem.Combine(paths.RathenaPath, "mapcache.exe");
        if (!File.Exists(toolPath))
        {
            return new MapCacheBuildResult(
                DateTimeOffset.UtcNow,
                false,
                toolPath,
                Path.GetFullPath(request.OutputCachePath),
                -1,
                false,
                ["mapcache.exe was not found in the rAthena root."]);
        }

        var workingRoot = Path.GetFullPath(request.WorkingRoot);
        EnsurePathInsideWorkspace(workingRoot);
        Directory.CreateDirectory(workingRoot);

        var outputCachePath = Path.GetFullPath(request.OutputCachePath);
        var seedCachePath = Path.GetFullPath(request.SeedCachePath);
        var mapListPath = Path.Combine(workingRoot, "map_list.txt");
        var grfListPath = Path.Combine(workingRoot, "grf_files.txt");

        File.WriteAllText(mapListPath, $"map: {request.MapName}{Environment.NewLine}", Encoding.ASCII);
        File.WriteAllText(grfListPath, BuildGrfList(paths), Encoding.UTF8);

        Directory.CreateDirectory(Path.GetDirectoryName(outputCachePath)!);
        if (!outputCachePath.Equals(seedCachePath, StringComparison.OrdinalIgnoreCase))
        {
            if (File.Exists(seedCachePath))
            {
                File.Copy(seedCachePath, outputCachePath, overwrite: true);
            }
            else if (File.Exists(outputCachePath))
            {
                File.Delete(outputCachePath);
            }
        }

        var arguments = BuildArguments(grfListPath, mapListPath, outputCachePath, File.Exists(seedCachePath));
        var startInfo = new ProcessStartInfo
        {
            FileName = toolPath,
            Arguments = arguments,
            WorkingDirectory = Path.GetFullPath(paths.RathenaPath),
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = Process.Start(startInfo)
                            ?? throw new InvalidOperationException("mapcache.exe could not be started.");
        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        var messages = new List<string>();
        if (!string.IsNullOrWhiteSpace(stdout))
        {
            messages.AddRange(SplitLines("stdout", stdout));
        }

        if (!string.IsNullOrWhiteSpace(stderr))
        {
            messages.AddRange(SplitLines("stderr", stderr));
        }

        var cacheExists = File.Exists(outputCachePath);
        var mapPresentInCache = cacheExists && MapCacheInspector.ContainsMap(outputCachePath, request.MapName);
        var succeeded = process.ExitCode == 0 && cacheExists && mapPresentInCache;

        if (!cacheExists)
        {
            messages.Add("mapcache.exe did not produce the requested cache file.");
        }
        else if (!mapPresentInCache)
        {
            messages.Add($"map_cache.dat was generated, but map '{request.MapName}' was not found in the cache payload.");
        }

        return new MapCacheBuildResult(
            DateTimeOffset.UtcNow,
            succeeded,
            toolPath,
            outputCachePath,
            process.ExitCode,
            mapPresentInCache,
            messages);
    }

    private static string BuildGrfList(RepositoryPaths paths)
    {
        var lines = new List<string>
        {
            "// Generated by RagnaForge for map cache staging",
            "data_dir: " + EnsureTrailingBackslash(Path.GetFullPath(Path.Combine(paths.PatchPath, "data")))
        };

        foreach (var grfFile in SafeFileSystem.EnumerateFiles(paths.GrfRepositoryPath, "*.grf", SearchOption.AllDirectories)
                     .OrderBy(file => file.FullName, StringComparer.OrdinalIgnoreCase))
        {
            lines.Add("grf: " + grfFile.FullName);
        }

        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    private static string BuildArguments(
        string grfListPath,
        string mapListPath,
        string outputCachePath,
        bool useSeedCache) =>
        useSeedCache
            ? $"-grf \"{grfListPath}\" -list \"{mapListPath}\" -cache \"{outputCachePath}\""
            : $"-grf \"{grfListPath}\" -list \"{mapListPath}\" -cache \"{outputCachePath}\" -rebuild";

    private static string EnsureTrailingBackslash(string path) =>
        path.EndsWith(Path.DirectorySeparatorChar) || path.EndsWith(Path.AltDirectorySeparatorChar)
            ? path
            : path + Path.DirectorySeparatorChar;

    private void EnsurePathInsideWorkspace(string fullPath)
    {
        var normalizedWorkspace = Path.GetFullPath(workspaceRoot);
        if (!fullPath.StartsWith(normalizedWorkspace + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)
            && !fullPath.Equals(normalizedWorkspace, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException($"Path is outside the workspace: {fullPath}");
        }
    }

    private static IReadOnlyList<string> SplitLines(string prefix, string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(line => $"{prefix}: {line}")
            .ToArray();
}

internal static class MapCacheInspector
{
    public static bool ContainsMap(string cachePath, string mapName)
    {
        using var stream = File.OpenRead(cachePath);
        using var reader = new BinaryReader(stream, Encoding.ASCII, leaveOpen: false);

        if (stream.Length < 6)
        {
            return false;
        }

        _ = reader.ReadUInt32();
        var mapCount = reader.ReadUInt16();
        for (var index = 0; index < mapCount; index++)
        {
            if (stream.Position + 20 > stream.Length)
            {
                return false;
            }

            var rawName = reader.ReadBytes(12);
            var cachedName = Encoding.ASCII.GetString(rawName).TrimEnd('\0', ' ');
            _ = reader.ReadInt16();
            _ = reader.ReadInt16();
            var compressedLength = reader.ReadInt32();
            if (compressedLength < 0 || stream.Position + compressedLength > stream.Length)
            {
                return false;
            }

            if (cachedName.Equals(mapName, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            stream.Seek(compressedLength, SeekOrigin.Current);
        }

        return false;
    }
}
